import importlib
import json
import subprocess
import sys
from pathlib import Path

import pytest

from agent.clarence_foundry.candidates import build_candidate_envelope

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "clarence_foundry_nightly.py"


class FakeRunner:
    def __init__(
        self,
        *,
        fail_step=None,
        timeout_step=None,
        stderr="",
        stdout="",
        candidate_symlink_step=None,
        symlink_run_id=None,
    ):
        self.calls = []
        self.fail_step = fail_step
        self.timeout_step = timeout_step
        self.stderr = stderr
        self.stdout = stdout
        self.candidate_symlink_step = candidate_symlink_step
        self.symlink_run_id = symlink_run_id

    def __call__(self, cmd, *, cwd=None, timeout=None, text=True, capture_output=True, check=False, env=None):
        cmd = [str(part) for part in cmd]
        self.calls.append(cmd)
        step = self._step_name(cmd)
        if self.timeout_step == step:
            raise subprocess.TimeoutExpired(cmd=cmd, timeout=timeout, output="partial", stderr="timeout")
        if self.fail_step == step:
            return subprocess.CompletedProcess(cmd, 1, stdout=self.stdout, stderr=self.stderr)
        if cmd[:2] == ["git", "--no-optional-locks"]:
            return self._git_result(cmd)
        if step == "reliability":
            return subprocess.CompletedProcess(cmd, 0, stdout=json.dumps({"ok": True, "cases": []}), stderr="")
        if step in {"self_audit", "skill_candidates", "routing_bench"}:
            candidate_json = self._candidate_json(cmd, step, env=env)
            return subprocess.CompletedProcess(cmd, 0, stdout=candidate_json, stderr="")
        raise AssertionError(f"unexpected command: {cmd}")

    def _step_name(self, cmd):
        if "agent.clarence_reliability.runner" in cmd:
            return "reliability"
        joined = " ".join(cmd)
        if "foundry_self_audit.py" in joined:
            return "self_audit"
        if "foundry_skill_candidates.py" in joined:
            return "skill_candidates"
        if "foundry_routing_bench.py" in joined:
            return "routing_bench"
        if cmd[:2] == ["git", "--no-optional-locks"]:
            return "git"
        return "unknown"

    def _git_result(self, cmd):
        if "rev-parse" in cmd and "--abbrev-ref" in cmd:
            return subprocess.CompletedProcess(cmd, 0, stdout="clarence/foundry-phase3-nightly-runner\n", stderr="")
        if "rev-parse" in cmd and "HEAD" in cmd:
            return subprocess.CompletedProcess(cmd, 0, stdout="abc123\n", stderr="")
        if "status" in cmd:
            return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")
        if "merge-base" in cmd:
            return subprocess.CompletedProcess(cmd, 0, stdout="base123\n", stderr="")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    def _candidate_json(self, cmd, step, env=None):
        if self.candidate_symlink_step == step:
            assert env is not None
            assert self.symlink_run_id is not None
            candidate_root = Path(env["HERMES_HOME"]) / "foundry" / "runs" / self.symlink_run_id / "candidates"
            escape = candidate_root.parent.parent / f"escaped-{step}"
            escape.mkdir(parents=True, exist_ok=True)
            if candidate_root.exists() and candidate_root.is_dir() and not candidate_root.is_symlink():
                candidate_root.rmdir()
            candidate_root.symlink_to(escape, target_is_directory=True)
        slug = cmd[cmd.index("--slug") + 1]
        kind = {
            "self_audit": "self_audit",
            "skill_candidates": "skill_candidates",
            "routing_bench": "routing_bench",
        }[step]
        candidate = build_candidate_envelope(
            kind=kind,
            title=f"{step} test candidate",
            summary="Generated by unit-test fake runner.",
            source={"script": f"scripts/foundry_{step}.py", "phase": "foundry-phase3-test"},
            payload={"step": step, "network_calls": "none"},
            slug=slug,
        )
        return json.dumps(candidate)


def import_nightly():
    return importlib.import_module("agent.clarence_foundry.nightly")


def test_importing_nightly_does_not_create_foundry(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))

    import_nightly()

    assert not (tmp_path / "hermes-home" / "foundry").exists()


def test_default_runs_root_honors_hermes_home(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "custom-home"))
    nightly = import_nightly()

    assert nightly.default_runs_root() == tmp_path / "custom-home" / "foundry" / "runs"


def test_default_run_id_is_valid_lowercase_slug():
    nightly = import_nightly()

    run_id = nightly.default_run_id()

    assert run_id == run_id.lower()
    assert nightly.validate_run_id(run_id) == run_id


@pytest.mark.parametrize("bad_run_id", ["", "../x", "/tmp/x", "foo/bar", "foo\\bar", "~secret", "two words"])
def test_validate_run_id_rejects_unsafe_values(bad_run_id):
    nightly = import_nightly()

    with pytest.raises(nightly.FoundryNightlyError):
        nightly.validate_run_id(bad_run_id)


def test_prepare_run_dir_rejects_collisions(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runs_root = nightly.default_runs_root()
    (runs_root / "existing").mkdir(parents=True)

    with pytest.raises(nightly.FoundryNightlyError):
        nightly.prepare_run_dir(run_id="existing", runs_root=runs_root)


def test_prepare_run_dir_rejects_symlink_escape(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    real_root = nightly.default_runs_root()
    escape_root = tmp_path / "escape"
    real_root.mkdir(parents=True)
    escape_root.mkdir()
    (real_root / "bad").symlink_to(escape_root, target_is_directory=True)

    with pytest.raises(nightly.FoundryNightlyError):
        nightly.prepare_run_dir(run_id="bad", runs_root=real_root)


def test_run_nightly_rejects_non_default_runs_root(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()

    with pytest.raises(nightly.FoundryNightlyError):
        nightly.run_nightly(
            repo_root=REPO_ROOT,
            run_id="outside-root",
            runs_root=tmp_path / "outside",
            command_runner=FakeRunner(),
        )


def test_successful_run_writes_only_under_run_dir(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner()

    summary = nightly.run_nightly(
        repo_root=REPO_ROOT,
        run_id="unit-success",
        command_runner=runner,
        timeout_seconds=10,
    )

    run_dir = tmp_path / "hermes-home" / "foundry" / "runs" / "unit-success"
    assert summary["ok"] is True
    assert summary["status"] == "passed"
    assert (run_dir / "summary.json").exists()
    assert (run_dir / "metadata" / "git.json").exists()
    assert (run_dir / "reliability" / "result.json").exists()
    assert len(sorted((run_dir / "candidates").rglob("*.json"))) == 3
    assert (run_dir / "routing_smoke" / "results.json").exists()
    assert not (tmp_path / "hermes-home" / "foundry" / "candidates").exists()
    assert not (tmp_path / "hermes-home" / "memories").exists()
    assert not (tmp_path / "hermes-home" / "skills").exists()
    assert not (tmp_path / "hermes-home" / "config.yaml").exists()
    assert not (tmp_path / "hermes-home" / "cron").exists()


def test_run_nightly_without_run_id_uses_safe_default(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()

    summary = nightly.run_nightly(repo_root=REPO_ROOT, command_runner=FakeRunner())

    assert summary["ok"] is True
    assert summary["run_id"] == summary["run_id"].lower()
    assert (tmp_path / "hermes-home" / "foundry" / "runs" / summary["run_id"] / "summary.json").exists()


def test_reliability_command_uses_json_and_run_local_manifest(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner()

    nightly.run_nightly(repo_root=REPO_ROOT, run_id="unit-reliability", command_runner=runner)

    reliability_calls = [call for call in runner.calls if "agent.clarence_reliability.runner" in call]
    assert len(reliability_calls) == 1
    call = reliability_calls[0]
    assert "--json" in call
    manifest = Path(call[call.index("--manifest") + 1])
    run_dir = tmp_path / "hermes-home" / "foundry" / "runs" / "unit-reliability"
    assert manifest == run_dir / "reliability" / "manifest.json"


def test_generator_commands_print_json_and_wrapper_writes_candidates(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner()

    summary = nightly.run_nightly(repo_root=REPO_ROOT, run_id="unit-generators", command_runner=runner)

    assert summary["ok"] is True
    generator_calls = [
        call
        for call in runner.calls
        if any(
            name in " ".join(call)
            for name in ["foundry_self_audit.py", "foundry_skill_candidates.py", "foundry_routing_bench.py"]
        )
    ]
    assert len(generator_calls) == 3
    run_dir = tmp_path / "hermes-home" / "foundry" / "runs" / "unit-generators"
    assert len(sorted((run_dir / "candidates").rglob("*.json"))) == 3
    for call in generator_calls:
        assert "--print-json" in call
        assert "--out-dir" not in call
        assert "--overwrite" not in call


def test_invalid_reliability_json_fails_closed_and_stops_downstream(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner(fail_step="reliability", stdout="not-json", stderr="")

    summary = nightly.run_nightly(repo_root=REPO_ROOT, run_id="unit-bad-json", command_runner=runner)

    assert summary["ok"] is False
    assert summary["failure_code"] in {"invalid_json", "command_failed"}
    assert not any("foundry_self_audit.py" in " ".join(call) for call in runner.calls)


def test_candidate_writer_rejection_fails_closed(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner(fail_step="self_audit", stderr="foundry_self_audit: candidate already exists")

    summary = nightly.run_nightly(repo_root=REPO_ROOT, run_id="unit-candidate-rejected", command_runner=runner)

    assert summary["ok"] is False
    assert summary["failure_code"] == "candidate_rejected"


def test_generator_created_candidate_symlink_escape_fails_without_outside_candidate_write(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner(candidate_symlink_step="self_audit", symlink_run_id="unit-symlink-candidate")

    summary = nightly.run_nightly(repo_root=REPO_ROOT, run_id="unit-symlink-candidate", command_runner=runner)

    escaped = tmp_path / "hermes-home" / "foundry" / "runs" / "escaped-self_audit"
    assert summary["ok"] is False
    assert summary["failure_code"] == "candidate_rejected"
    assert not list(escaped.rglob("*.json"))


def test_timeout_fails_closed(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()
    runner = FakeRunner(timeout_step="reliability")

    summary = nightly.run_nightly(repo_root=REPO_ROOT, run_id="unit-timeout", command_runner=runner, timeout_seconds=1)

    assert summary["ok"] is False
    assert summary["failure_code"] == "timeout"


def test_quota_and_model_5xx_fail_closed(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))
    nightly = import_nightly()

    quota = nightly.run_nightly(
        repo_root=REPO_ROOT,
        run_id="unit-quota",
        command_runner=FakeRunner(fail_step="routing_bench", stderr="quota exceeded: billing hard limit"),
    )
    storm = nightly.run_nightly(
        repo_root=REPO_ROOT,
        run_id="unit-5xx",
        command_runner=FakeRunner(fail_step="routing_bench", stderr="HTTP 500 then HTTP 503"),
    )

    assert quota["ok"] is False
    assert quota["failure_code"] == "quota_error"
    assert storm["ok"] is False
    assert storm["failure_code"] == "model_5xx_storm"


def test_cli_help_does_not_create_artifacts(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path / "hermes-home"))

    result = subprocess.run([sys.executable, str(SCRIPT_PATH), "--help"], cwd=REPO_ROOT, text=True, capture_output=True, check=False)

    assert result.returncode == 0
    assert "local-only" in result.stdout.lower()
    assert not (tmp_path / "hermes-home" / "foundry").exists()


def test_cli_without_run_id_uses_safe_default_and_writes_run_artifacts(tmp_path, monkeypatch):
    home = tmp_path / "hermes-home"
    monkeypatch.setenv("HERMES_HOME", str(home))

    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), "--repo-root", str(REPO_ROOT), "--allow-dirty", "--timeout-seconds", "60"],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    run_root = home / "foundry" / "runs"
    runs = list(run_root.iterdir())
    assert len(runs) == 1
    assert runs[0].name == runs[0].name.lower()
    assert (runs[0] / "summary.json").exists()
